[default]
pass_k = []
avg_k = [8]
report_pass_k = []
report_avg_k = [8]

[cot]
template = "free_response_cot_default"
temperature = 0.3
top_k = 500
top_p = 0.4

[final]
template = "free_response_final_default"
