[default]
pass_k = []
avg_k = [8]
report_pass_k = []
report_avg_k = [8]

[cot]
template = "free_response_cot_default"
max_generate_tokens = 3072
temperature = 0.3
top_k = 500
top_p = 0.3
alpha_presence = 1.0
alpha_frequency = 0.3
alpha_decay = 0.99

[final]
template = "free_response_final_default"
