CREATE TABLE IF NOT EXISTS benchmark (
    benchmark_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    benchmark_name VARCHAR(255) NOT NULL,
    benchmark_split VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    num_samples INT4 NOT NULL,
    CONSTRAINT chk_benchmark_status
        CHECK (status IN ('Todo', 'Buggy', 'Low', 'DataSynthesizing', 'Completed')),
    CONSTRAINT uq_benchmark_name_split UNIQUE (benchmark_name, benchmark_split)
);

CREATE TABLE IF NOT EXISTS model (
    model_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data_version VARCHAR(255) NOT NULL,
    arch_version VARCHAR(255) NOT NULL,
    num_params VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_model_identity UNIQUE (arch_version, data_version, num_params, model_name)
);

CREATE TABLE IF NOT EXISTS task (
    task_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    config_path VARCHAR(255),
    evaluator VARCHAR(255) NOT NULL,
    is_param_search BOOLEAN NOT NULL DEFAULT FALSE,
    is_tmp BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    git_hash VARCHAR(255) NOT NULL,
    model_id INT4 NOT NULL REFERENCES model(model_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    benchmark_id INT4 NOT NULL REFERENCES benchmark(benchmark_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    "desc" TEXT,
    sampling_config JSONB,
    log_path VARCHAR(255) NOT NULL,
    CONSTRAINT chk_task_status CHECK (status IN ('Running', 'Completed', 'Failed'))
);

CREATE TABLE IF NOT EXISTS completions (
    completions_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INT4 NOT NULL REFERENCES task(task_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    context JSONB NOT NULL,
    sample_index INT4 NOT NULL,
    avg_repeat_index INT4 NOT NULL,
    pass_index INT4 NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT chk_completions_sample_index CHECK (sample_index >= 0),
    CONSTRAINT chk_completions_avg_repeat_index CHECK (avg_repeat_index >= 0),
    CONSTRAINT chk_completions_pass_index CHECK (pass_index >= 0),
    CONSTRAINT chk_completions_status CHECK (status IN ('Running', 'Completed', 'Failed'))
);

CREATE TABLE IF NOT EXISTS eval (
    eval_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    completions_id INT4 NOT NULL REFERENCES completions(completions_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    answer TEXT NOT NULL,
    ref_answer TEXT NOT NULL,
    is_passed BOOLEAN NOT NULL,
    fail_reason TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_eval_completion UNIQUE (completions_id)
);

CREATE TABLE IF NOT EXISTS checker (
    checker_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    completions_id INT4 NOT NULL REFERENCES completions(completions_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    answer_correct BOOLEAN NOT NULL DEFAULT FALSE,
    instruction_following_error BOOLEAN NOT NULL DEFAULT FALSE,
    world_knowledge_error BOOLEAN NOT NULL DEFAULT FALSE,
    math_error BOOLEAN NOT NULL DEFAULT FALSE,
    reasoning_logic_error BOOLEAN NOT NULL DEFAULT FALSE,
    thought_contains_correct_answer BOOLEAN NOT NULL DEFAULT FALSE,
    needs_human_review BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_checker_completion UNIQUE (completions_id)
);

CREATE TABLE IF NOT EXISTS scores (
    score_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INT4 NOT NULL REFERENCES task(task_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    cot_mode VARCHAR(32) NOT NULL,
    metrics JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_scores_cot_mode CHECK (cot_mode IN ('NoCoT', 'FakeCoT', 'CoT')),
    CONSTRAINT uq_score_task UNIQUE (task_id)
);

CREATE INDEX IF NOT EXISTS idx_task_model ON task(model_id);
CREATE INDEX IF NOT EXISTS idx_task_benchmark ON task(benchmark_id);
CREATE INDEX IF NOT EXISTS idx_task_is_tmp_created_at ON task(is_tmp, created_at);
CREATE INDEX IF NOT EXISTS idx_task_status_created_at ON task(status, created_at);
CREATE INDEX IF NOT EXISTS idx_task_identity_lookup ON task(model_id, benchmark_id, evaluator, git_hash, config_path);
CREATE INDEX IF NOT EXISTS idx_completions_task ON completions(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_completions_sample
    ON completions(task_id, sample_index, avg_repeat_index, pass_index);
CREATE INDEX IF NOT EXISTS idx_eval_completion ON eval(completions_id);
CREATE INDEX IF NOT EXISTS idx_checker_completion ON checker(completions_id);
CREATE INDEX IF NOT EXISTS idx_checker_needs_human_review ON checker(needs_human_review);
CREATE INDEX IF NOT EXISTS idx_scores_task ON scores(task_id);

CREATE OR REPLACE VIEW view_model_version AS
SELECT
    model_id,
    model_name,
    arch_version,
    data_version,
    num_params,
    concat_ws('_', arch_version, data_version, num_params) AS model_version
FROM model;
