CREATE TABLE IF NOT EXISTS benchmark (
    benchmark_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    benchmark_name VARCHAR(255) NOT NULL,
    benchmark_split VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    num_samples VARCHAR(255) NOT NULL,
    CONSTRAINT chk_benchmark_status
        CHECK (status IN ('Todo', 'Buggy', 'Low', 'DataSynthesizing', 'Completed'))
);

CREATE TABLE IF NOT EXISTS model (
    model_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data_version VARCHAR(255) NOT NULL,
    arch_version VARCHAR(255) NOT NULL,
    num_params VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
    task_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    config_path VARCHAR(255),
    evaluator VARCHAR(255) NOT NULL,
    is_param_search BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    git_hash VARCHAR(255) NOT NULL,
    model_id INT4 NOT NULL REFERENCES model(model_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    benchmark_id INT4 NOT NULL REFERENCES benchmark(benchmark_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    "desc" TEXT,
    sampling_config JSONB,
    log_path VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS completions (
    completions_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INT4 NOT NULL REFERENCES task(task_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    context JSONB NOT NULL,
    sample_index VARCHAR(255) NOT NULL,
    repeat_index VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS eval (
    eval_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    completions_id INT4 NOT NULL REFERENCES completions(completions_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    answer TEXT NOT NULL,
    ref_answer TEXT NOT NULL,
    is_passed BOOLEAN NOT NULL,
    fail_reason TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
    score_id INT4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INT4 NOT NULL REFERENCES task(task_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    is_cot BOOLEAN NOT NULL,
    metrics JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_task_model ON task(model_id);
CREATE INDEX IF NOT EXISTS idx_task_benchmark ON task(benchmark_id);
CREATE INDEX IF NOT EXISTS idx_completions_task ON completions(task_id);
CREATE INDEX IF NOT EXISTS idx_eval_completion ON eval(completions_id);
CREATE INDEX IF NOT EXISTS idx_scores_task ON scores(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_completions_sample ON completions(task_id, sample_index, repeat_index);

CREATE OR REPLACE VIEW view_model_version AS
SELECT
    model_id,
    model_name,
    arch_version,
    data_version,
    num_params,
    concat_ws('_', arch_version, data_version, num_params) AS model_version
FROM model;
